#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Vedant ashtikar | Course: Open Source Software
# Purpose: Generate a personalised open-source philosophy
#          statement based on user input and save it to a file.
#
# Alias tip: add to ~/.bashrc to run quickly:
#   alias manifesto='bash ~/oss_scripts/script5_manifesto.sh'
# ============================================================

echo "========================================================"
echo "     The Open Source Manifesto Generator"
echo "     VIT Bhopal | Open Source Software Course"
echo "========================================================"
echo ""
echo "Answer three questions. Your manifesto will be generated."
echo ""

# --- Collect user responses interactively ---
# 'read -p' displays a prompt and stores the input in a variable
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you?  " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# --- Generate metadata ---
DATE=$(date '+%d %B %Y')             # Formatted date for the manifesto
USER_NAME=$(whoami)                  # Current user's system name
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')  # Timestamp for unique filename

# Output file named uniquely per user and timestamp
OUTPUT="manifesto_${USER_NAME}_${TIMESTAMP}.txt"

# --- Compose the manifesto paragraph using string variables ---
# Using > to create the file (overwrites if it exists)
# Using >> to append subsequent lines to the file

echo "========================================================" > "$OUTPUT"
echo "          OPEN SOURCE MANIFESTO"                         >> "$OUTPUT"
echo "          Generated by: $USER_NAME"                      >> "$OUTPUT"
echo "          Date: $DATE"                                   >> "$OUTPUT"
echo "========================================================"  >> "$OUTPUT"
echo ""                                                         >> "$OUTPUT"

# Concatenate user answers into a composed paragraph
echo "Every day, I rely on $TOOL — a piece of software that"   >> "$OUTPUT"
echo "someone built, shared, and gave to the world without"    >> "$OUTPUT"
echo "asking for anything in return. To me, freedom means"     >> "$OUTPUT"
echo "$FREEDOM."                                               >> "$OUTPUT"
echo ""                                                         >> "$OUTPUT"
echo "I believe that code, like knowledge, grows stronger when" >> "$OUTPUT"
echo "it is shared. That is why I would build $BUILD and"      >> "$OUTPUT"
echo "release it openly — not because I am required to, but"   >> "$OUTPUT"
echo "because the software I depend on every day was built by"  >> "$OUTPUT"
echo "people who made the same choice before me."              >> "$OUTPUT"
echo ""                                                         >> "$OUTPUT"
echo "Open source is not just a licensing model. It is an"     >> "$OUTPUT"
echo "argument about how knowledge should move through the"    >> "$OUTPUT"
echo "world."                                                  >> "$OUTPUT"
echo ""                                                         >> "$OUTPUT"
echo "                    — $USER_NAME, $DATE"                 >> "$OUTPUT"
echo "========================================================"  >> "$OUTPUT"

# --- Display the result ---
echo ""
echo "Manifesto saved to: $OUTPUT"
echo ""
cat "$OUTPUT"
